### ISSUE TITLE
Add support for watching multiple files with --watch option

### ISSUE THREAD

**Issue by AbhimanyuG** [danielgtaylor/apisprout#33]
It'll be helpful if specs are distributed across multiple files.

**Comment by danielgtaylor** [comment]
Nice idea! This *might* also be possible by parsing the refs in the file, which would mean supporting watching files across different directories instead of assuming all the files are in one place.

**Comment by AbhimanyuG** [comment]
> Nice idea! This _might_ also be possible by parsing the refs in the file, which would mean supporting watching files across different directories instead of assuming all the files are in one place.

Yea, that makes more sense. 

For anyone looking for workaround right now, here's a pm2 wrapper Dockerfile and command:

Dockerfile:
```
FROM danielgtaylor/apisprout
RUN apk update && apk add nodejs npm && npm i -g pm2
```



docker-compose.yml
```
 api-mock:
    build: ./dir
    volumes:
      - "./dir:/api-specs"
    entrypoint: "pm2 start apisprout --no-daemon --watch /api-specs/ -- /api-specs/openapi.yaml"
```
