### ISSUE TITLE
Media Types with charset not accepted

### ISSUE THREAD

**Issue by buuhuu** [danielgtaylor/apisprout#66]
Having a media type containing the optional charset part lets the mock server fail. 

```
2020/02/10 14:46:31 GET /health (checkHealth) => 200 (application/json;charset=UTF-8)
2020/02/10 14:46:31 Cannot marshal as 'application/json;charset=UTF-8'!
```

With the following spec for example

```
/pet/findByStatus:
    get:
      tags:
      - "pet"
      summary: "Finds Pets by status"
      description: "Multiple status values can be provided with comma separated strings"
      operationId: "findPetsByStatus"
      produces:
      - "application/json; charset=utf-8"
```
